### ISSUE TITLE
The download link for 1KG_ref_ricopili doesn't work with cURL or wget

### ISSUE THREAD

**Issue by kkarbasi** [bruggerk/ricopili_docker#3]
When I run the 
`curl -LO https://storage.cloud.google.com/cloud-ricopili/reference-genotypes/1KG_ref_ricopili.tar.gz
`
command it does not download the complete file. Seems like it downloads the google authentication page instead.

**Comment by bruggerk** [comment]
Not controlled by me, have updated documentation accordingly
